//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVCB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int MSBK { get; set; }
        public string MABK { get; set; }
        public string MAKH { get; set; }
        public string MANV { get; set; }
        public string MAVB { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual VEBAY VEBAY { get; set; }
    }
}
