//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVCB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENBAY()
        {
            this.VEBAYs = new HashSet<VEBAY>();
        }
    
        public string MACB { get; set; }
        public string MAMB { get; set; }
        public Nullable<System.DateTime> THOIGIAN_CATCANH { get; set; }
        public Nullable<System.DateTime> THOIGIAN_HACANH { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> SO_GHE { get; set; }
        public string MASB_CATCANH { get; set; }
        public string MASB_HACANH { get; set; }
    
        public virtual MAYBAY MAYBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEBAY> VEBAYs { get; set; }
    }
}
