//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVCB.Model
{
    using QLBVCB.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DADAT : VM_Base
    {
        private string _MACB;
        public string MACB { get => _MACB; set { _MACB = value; OnPropertyChanged(); } }

        private int _Hang;
        public int Hang { get => _Hang; set { _Hang = value; OnPropertyChanged(); } }

        private int _Day;
        public int Day { get => _Day; set { _Day = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _NGTHANHTOAN;
        public Nullable<System.DateTime> NGTHANHTOAN { get => _NGTHANHTOAN; set { _NGTHANHTOAN = value; OnPropertyChanged(); } }

        private string _MABK;
        public string MABK { get => _MABK; set { _MABK = value; OnPropertyChanged(); } }

        private string _MAKH;
        public string MAKH { get => _MAKH; set { _MAKH = value; OnPropertyChanged(); } }

        private string _MAVB;
        public string MAVB { get => _MAVB; set { _MAVB = value; OnPropertyChanged(); } }

        private string _MASA;
        public string MASA { get => _MASA; set { _MASA = value; OnPropertyChanged(); } }

        private string _TENHANHKHACH;
        public string TENHANHKHACH { get => _TENHANHKHACH; set { _TENHANHKHACH = value; OnPropertyChanged(); } }

        private string _MAHL;
        public string MAHL { get => _MAHL; set { _MAHL = value; OnPropertyChanged(); } }

        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual DICHVU DICHVU { get; set; }
        public virtual DICHVU DICHVU1 { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VEBAY VEBAY { get; set; }
    }
}
