//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVCB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DADAT
    {
        public string MACB { get; set; }
        public int Hang { get; set; }
        public int Day { get; set; }
        public string MABK { get; set; }
        public string MAKH { get; set; }
        public string MAVB { get; set; }
        public string MASA { get; set; }
        public string MAHL { get; set; }
        public Nullable<System.DateTime> NGTHANHTOAN { get; set; }
        public string TENHANHKHACH { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual DICHVU DICHVU { get; set; }
        public virtual DICHVU DICHVU1 { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VEBAY VEBAY { get; set; }
    }
}
