//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVCB.Model
{
    using QLBVCB.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class VEBAY : VM_Base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEBAY()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
        }

        private int _MSVB;
        public int MSVB { get => _MSVB; set { _MSVB = value; OnPropertyChanged(); } }

        private string _MAVB;
        public string MAVB { get => _MAVB; set { _MAVB = value; OnPropertyChanged(); } }

        private string _MACB;
        public string MACB { get => _MACB; set { _MACB = value; OnPropertyChanged(); } }

        private string _THUTU_GHE;
        public string THUTU_GHE { get => _THUTU_GHE; set { _THUTU_GHE = value; OnPropertyChanged(); } }

        private string _MALV;
        public string MALV { get => _MALV; set { _MALV = value; OnPropertyChanged(); } }

        private Nullable<bool> _DADAT;
        public Nullable<bool> DADAT { get => _DADAT; set { _DADAT = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
