//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVCB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEBAY()
        {
            this.DADATs = new HashSet<DADAT>();
        }
    
        public string MAVB { get; set; }
        public string MACB { get; set; }
        public string THUTU_GHE { get; set; }
        public string MALV { get; set; }
        public Nullable<bool> DADAT { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DADAT> DADATs { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
